version: '3'
services:
  server:
    container_name: sky-com-test
    build: .
    ports:
      - 8080:5000
    env_file:
      - .env
    links:
      - database
  database:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
